from pydantic import BaseModel, Field

class EmployeeFeatures(BaseModel):
    """
    Pydantic request body mapping input features for an employee.
    Includes validation constraints for fields where applicable.
    """
    employee_name: str = Field(
        ..., 
        description="The full name of the employee being evaluated"
    )
    overtime_flag: int = Field(
        ..., 
        ge=0, 
        le=1, 
        description="Indicates if the employee works overtime: 1 (Yes) or 0 (No)"
    )
    years_at_company: float = Field(
        ..., 
        ge=0, 
        description="Number of years the employee has spent at the company"
    )
    distance_from_home: float = Field(
        ..., 
        ge=0, 
        description="Commuting distance in miles or kilometers"
    )
    monthly_income: float = Field(
        ..., 
        ge=0, 
        description="Monthly gross salary of the employee"
    )


class RiskPrediction(BaseModel):
    """
    Pydantic response payload containing machine learning calculations 
    and customized qualitative generative AI suggestions.
    """
    risk_score: float = Field(
        ..., 
        description="Predicted percentage probability of attrition risk, rounded to 1 decimal place"
    )
    risk_category: str = Field(
        ..., 
        description="Risk range category: LOW, MEDIUM, or HIGH"
    )
    top_factors: list[str] = Field(
        ..., 
        description="The top features contributing to the prediction based on global feature importances"
    )
    ai_insight: str = Field(
        ..., 
        description="Qualitative HR context generated by Gemini, explaining the risk factors and suggested actions"
    )
